replicaCount: 1

backend:
  image: shreybatra/sample-backend
  env:
    REDIS_URI: redis://redis-svc:6379
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  env:
    BACKEND_URL: http://backend-svc:8000
  service:
    type: NodePort
    port: 5173
    nodePort: 31000

redis:
  image: redis
  service:
    type: ClusterIP
    port: 6379

resources: {}
