apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
  selector:
    app: backend

